---
- name: Setup Jenkins on ARM architecture
  hosts: gitops1
  become: true

  tasks:
    - name: Create Docker volume for Jenkins
      command: docker volume create jenkins-data
      register: jenkins_volume
      changed_when: false

    - name: Ensure Docker network for Jenkins exists
      docker_network:
        name: jenkins-network
        state: present

    - name: Stop existing Jenkins container if it exists
      shell: |
        docker stop jenkins || true
      ignore_errors: true

    - name: Remove existing Jenkins container if it exists
      shell: |
        docker rm jenkins || true
      ignore_errors: true

    - name: Run Jenkins container
      shell: |
        docker run -d --name jenkins \
          --network jenkins-network \
          -p 8081:8080 -p 50000:50000 \
          -v jenkins-data:/var/jenkins_home \
          -v /var/run/docker.sock:/var/run/docker.sock \
          jenkins/jenkins:lts
      args:
        executable: /bin/bash

    - name: Wait for Jenkins to initialize
      pause:
        seconds: 60

    - name: Wait for Jenkins initial admin password file to be created
      wait_for:
        path: /var/lib/docker/volumes/jenkins-data/_data/secrets/initialAdminPassword
        state: present
        timeout: 300

    - name: Get Jenkins initial admin password
      shell: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_admin_password
      changed_when: false

    - name: Display Jenkins initial admin password
      debug:
        var: jenkins_admin_password.stdout

    - name: Add Docker GPG key inside Jenkins container
      shell: |
        docker exec -u root jenkins bash -c "
          mkdir -p /etc/apt/keyrings &&
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
        "
      args:
        executable: /bin/bash

    - name: Add Docker repository inside Jenkins container
      shell: |
        docker exec -u root jenkins bash -c "
          echo 'deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable' > /etc/apt/sources.list.d/docker.list
        "
      args:
        executable: /bin/bash

    - name: Update apt cache inside Jenkins container
      shell: docker exec -u root jenkins apt-get update
      args:
        executable: /bin/bash

    - name: Install Docker CLI inside Jenkins container
      shell: docker exec -u root jenkins apt-get install -y docker-ce-cli
      args:
        executable: /bin/bash

    - name: Create docker group inside Jenkins container
      shell: docker exec -u root jenkins groupadd docker || true
      args:
        executable: /bin/bash

    - name: Add jenkins user to docker group
      shell: docker exec -u root jenkins usermod -aG docker jenkins
      args:
        executable: /bin/bash

    - name: Adjust permissions for Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Stop Jenkins container
      docker_container:
        name: jenkins
        state: stopped

    - name: Start Jenkins container
      docker_container:
        name: jenkins
        state: started
