---
- name: Configure and Run Prometheus with Exporters on gitops1
  hosts: gitops1
  become: true

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Create Prometheus user
      user:
        name: prometheus
        system: yes
        shell: /bin/false

    - name: Create directories for Prometheus and Exporters
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /opt/prometheus
        - /opt/alertmanager
        - /opt/mysqld_exporter
        - /opt/nginx_prometheus_exporter

    - name: Download and install Prometheus
      shell: |
        wget https://github.com/prometheus/prometheus/releases/download/v2.53.3/prometheus-2.53.3.linux-arm64.tar.gz -O /tmp/prometheus.tar.gz
        tar -xvf /tmp/prometheus.tar.gz -C /opt/
        mv /opt/prometheus-2.53.3.linux-arm64/* /opt/prometheus/
      args:
        creates: /opt/prometheus/prometheus

    - name: Configure Prometheus with dynamic targets
      copy:
        dest: /opt/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          alerting:
            alertmanagers:
              - static_configs:
                  - targets: ["{{ hostvars['gitops2']['ansible_host'] }}:9093"]

          scrape_configs:
            - job_name: "prometheus"
              static_configs:
                - targets: ["{{ hostvars['gitops1']['ansible_host'] }}:9090"]

            - job_name: "node_exporter"
              static_configs:
                - targets: ["{{ hostvars['gitops2']['ansible_host'] }}:9100"]

            - job_name: "cAdvisor"
              static_configs:
                - targets: ["{{ hostvars['gitops2']['ansible_host'] }}:8080"]

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          ExecStart=/opt/prometheus/prometheus \
            --config.file=/opt/prometheus/prometheus.yml \
            --storage.tsdb.path=/opt/prometheus/data \
            --web.console.templates=/opt/prometheus/consoles \
            --web.console.libraries=/opt/prometheus/console_libraries \
            --web.listen-address=0.0.0.0:9090
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start Prometheus service
      ansible.builtin.systemd:
        daemon_reload: true
        name: prometheus
        enabled: true
        state: started
