---
- name: Install and configure monitoring tools
  hosts: gitops1
  become: true

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Create Prometheus directory
      file:
        path: /opt/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Download and install Prometheus
      shell: |
        wget https://github.com/prometheus/prometheus/releases/download/v2.53.3/prometheus-2.53.3.linux-arm64.tar.gz -O /tmp/prometheus.tar.gz
        tar -xvf /tmp/prometheus.tar.gz -C /opt/
        mv /opt/prometheus-2.53.3.linux-arm64/* /opt/prometheus/
      args:
        creates: /opt/prometheus/prometheus

    - name: Configure Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          ExecStart=/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.path=/opt/prometheus/data
          User=prometheus
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started

    - name: Download and install Alertmanager
      shell: |
        wget https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-arm64.tar.gz -O /tmp/alertmanager.tar.gz
        tar -xvf /tmp/alertmanager.tar.gz -C /opt/
        mv /opt/alertmanager-0.27.0.linux-arm64 /opt/alertmanager
      args:
        creates: /opt/alertmanager/alertmanager

    - name: Configure Alertmanager systemd service
      copy:
        dest: /etc/systemd/system/alertmanager.service
        content: |
          [Unit]
          Description=Alertmanager
          After=network.target

          [Service]
          ExecStart=/opt/alertmanager/alertmanager --config.file=/opt/alertmanager/alertmanager.yml
          User=prometheus
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Alertmanager service
      systemd:
        name: alertmanager
        enabled: yes
        state: started

    - name: Download and install mysqld_exporter
      shell: |
        wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.16.0/mysqld_exporter-0.16.0.linux-arm64.tar.gz -O /tmp/mysqld_exporter.tar.gz
        tar -xvf /tmp/mysqld_exporter.tar.gz -C /opt/
        mv /opt/mysqld_exporter-0.16.0.linux-arm64 /opt/mysqld_exporter
      args:
        creates: /opt/mysqld_exporter/mysqld_exporter

    - name: Configure mysqld_exporter systemd service
      copy:
        dest: /etc/systemd/system/mysqld_exporter.service
        content: |
          [Unit]
          Description=mysqld_exporter
          After=network.target

          [Service]
          ExecStart=/opt/mysqld_exporter/mysqld_exporter --config.my-cnf=/opt/mysqld_exporter/.my.cnf
          User=prometheus
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start mysqld_exporter service
      systemd:
        name: mysqld_exporter
        enabled: yes
        state: started

    - name: Download and install node_exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-arm64.tar.gz -O /tmp/node_exporter.tar.gz
        tar -xvf /tmp/node_exporter.tar.gz -C /opt/
        mv /opt/node_exporter-1.8.2.linux-arm64 /opt/node_exporter
      args:
        creates: /opt/node_exporter/node_exporter

    - name: Configure node_exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=node_exporter
          After=network.target

          [Service]
          ExecStart=/opt/node_exporter/node_exporter
          User=prometheus
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start node_exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started

    - name: Download and install nginx_prometheus_exporter
      shell: |
        wget https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_linux_arm64.tar.gz -O /tmp/nginx_prometheus_exporter.tar.gz
        mkdir -p /opt/nginx_prometheus_exporter
        tar -xvf /tmp/nginx_prometheus_exporter.tar.gz -C /opt/nginx_prometheus_exporter --strip-components=1
      args:
        creates: /opt/nginx_prometheus_exporter/nginx-prometheus-exporter
      register: nginx_exporter_result
      ignore_errors: yes

    - name: Debug nginx_prometheus_exporter installation result
      debug:
        var: nginx_exporter_result

    - name: Configure nginx_prometheus_exporter systemd service
      copy:
        dest: /etc/systemd/system/nginx_prometheus_exporter.service
        content: |
          [Unit]
          Description=nginx_prometheus_exporter
          After=network.target

          [Service]
          ExecStart=/opt/nginx_prometheus_exporter/nginx-prometheus-exporter --nginx.scrape-uri=http://localhost:8085/stub_status
          User=prometheus
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start nginx_prometheus_exporter service
      systemd:
        name: nginx_prometheus_exporter
        enabled: yes
        state: started

    - name: Display status of all services
      shell: |
        systemctl status prometheus alertmanager mysqld_exporter node_exporter nginx_prometheus_exporter || true
      register: service_status
      changed_when: false
      ignore_errors: yes

    - name: Display service statuses
      debug:
        var: service_status.stdout_lines
